### ISSUE TITLE
Add unit tests for ConvertTypes

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#112]
I didn't see any explicit calls to the converters in [ConvertTypes](https://github.com/scijava/incubator/blob/ad1535415a4dd36eb5837ccde9e6e7bca749e42f/imagej/imagej-ops2/src/main/java/net/imagej/ops2/convert/ConvertTypes.java#L61)... are they being tested indirectly?

If not, they seem fairly fundamental and should be tested.

**Comment by ctrueden** [comment]
Alison wrote very thorough tests when she added this to Ops v1. They are template-generated, [here](https://github.com/imagej/imagej-ops/tree/imagej-ops-0.49.1/src/main/templates/net/imagej/ops/convert). But I can't find any trace of that code in the incubator... maybe it never got ported over?

**Comment by imagejan** [comment]
See [here](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.49.1/src/test/templates/net/imagej/ops/convert/ConvertImagesTest.vm) for the template-generated *tests* (the link above points to the main classes).

**Comment by ctrueden** [comment]
Ahh whoops, thanks @imagejan!

**Comment by ctrueden** [comment]
Also: there are two conversion test templates, one for images, and one for types. It looks like I'm actually the person that wrote the one for images; who knew? But Alison wrote the `TestConvertType` template.

**Comment by gselzer** [comment]
I migrated the template to ImageJ Ops2 [on this branch](https://github.com/scijava/incubator/tree/imagej/imagej-ops2/add-convert-type-tests). Unfortunately, the Op calls `ops.unary("convert.x").input(b).apply()` don't match because all of the `ConvertTypes` Ops are `Computer`s, and there's no way to write `create` Ops in a way to prevent multiple matches.

So, to close out this issue, we need to either:
1) Change the tests to match on *at least* `ops.unary("convert.x").input(b).outType(X.class).apply()`, which kinda sucks - it'd be nice if we could avoid the class, but maybe it's alright.
2) Write a `Function` wrapper around each `Computer` - that sounds *horrible*, and it's what we were hoping to get around with adaptation, but at least it would work.
3) Some other option I haven't thought of.

Thoughts @hinerm @ctrueden? I'm tentatively going to choose Option 1 because it should be significantly easier to implement, but we will have the same issue operating on the Image level :frowning:
