### ISSUE TITLE
Improve OpInfo.opString output

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#116]
See [opString](https://github.com/scijava/incubator/blob/7f6f07c31198ee7eb25ea02d954cd7deff0e2341/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/OpInfo.java#L133)

- [x] add question mark on optional params
- [x] List containers once and not in both inputs/outputs

**Comment by ctrueden** [comment]
I'd like to see the op stringification logic externalized somehow, instead of baked into the interface. The reasons are:
* The stringification logic adds a lot of code to the interface, making the interface contract it harder to read and understand.
* The requirements for stringification differ across applications: we need detailed strings with typing for devs, simpler strings with higher level concepts for scripters, and potentially other representations for other scenarios. Having the logic for each of these scenarios well-separated is nicer, IMHO.
