### ISSUE TITLE
Assess feasibility of Ops with all ImgLib2 image types

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#122]
When reviewing https://github.com/scijava/incubator/pull/76 I was curious about its specializations for `ArrayImg`. I noticed we only have a `copy` Op for [ArrayImgs](https://github.com/scijava/incubator/blob/ab0b1455fd585235aaba378ae1e72406c1469eca/imagej/imagej-ops2/src/main/java/net/imagej/ops2/copy/CopyArrayImg.java) and when I tried making a version of [CopyArrayImgTest](https://github.com/scijava/incubator/blob/ab0b1455fd585235aaba378ae1e72406c1469eca/imagej/imagej-ops2/src/test/java/net/imagej/ops2/copy/CopyArrayImgTest.java) for `PlanarImg` it failed.

It seems like we want to ensure all `Img` types are supported, at least with a slow fallback.

**Comment by hinerm** [comment]
@gselzer am I off-base here? Is there a reason these operations just shouldn't be supported for other `Img` types?

**Comment by gselzer** [comment]
@hinerm they *are* supported, just not using the `Op` name `copy.img`, because I removed the `copy.img` Ops in scijava/incubator#76, and now the only `Op` with that name is the one that works on `ArrayImg`s :sweat_smile: 

The solution is probably to alias `copy.rai`, and also `copy.iterableInterval` to `copy.img`, or just to always use `copy`. I created a test clone on `PlanarImg`, and changed the name to `copy` and things worked just fine.

I'll file a PR to fix the copy namespace!

**Comment by ctrueden** [comment]
Without thinking deeply about it, I like the idea of all copy ops just being `copy`. If you want to copy to a particular destination type, and it supports the computer paradigm, you can just pass the empty container of desired type. Is there ever a case where you might want to clone an object to a new type of your choosing, but can't create a new object of that type for use as a container? E.g. "copy" a `FloatType` to a `Double`? (`Double` is immutable so can't support the computer paradigm.)

**Comment by hinerm** [comment]
Closed in https://github.com/scijava/incubator/pull/77
