### ISSUE TITLE
Write Tutorial using Nils in Ops

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#133]
In the [Calling Ops](https://github.com/scijava/incubator/blob/main/imagej/imagej-ops2-tutorial/docs/CallingOps.md) document I'd like to see an example explaining why and how to use `Nil` types in Op calls.

**Comment by ctrueden** [comment]
Issues such as #134 illustrate how sometimes, the matcher fails when given only objects; therefore, teaching people how to matching using types alone is a nice thing to do. However, matching with `Nil`s is scary for beginners because it involves generics—and furthermore, usage of Java generics from certain scripting languages cannot be done, and therefore `Nil` cannot be used as intended in languages like Jython.

That said, we do still want to showcase "matching with types alone" in an Advanced section of the tutorial. This should show matching with `Class` first, and only afterward move on to `Nil`, with the caveat that it's "Java-centric" code-wise. (We can test [whether generics work in Groovy](https://groovy-lang.org/objectorientation.html#generics)...)

**Comment by gselzer** [comment]
@hinerm can we consider this closed with the merge of scijava/incubator#14? I wrote [this main class](https://github.com/scijava/incubator/pull/14/files#diff-a25c00c6b66e7a84b66475cc75bb427051a196c9e3d53e6d5e76b5a8235a14ec)...
