### ISSUE TITLE
ImageJ-Ops2 unit tests fail when compilation not part of life-cycle

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava#141]
When building the incubator reactor from the top level with a life-cycle target that includes compilation and testing, e.g. `mvn clean install`, all components build and all tests pass. However, `imagej/imagej-ops2` tests *always* seem fail if they are not run as part of a build process. For example running `mvn test` at the top level will result in these tests failing.

**Comment by gselzer** [comment]
So, they don't *always* fail.

The failures you see are due to how we merge the `op.yaml` files from source to test - when you don't run the `clean` goal, you maintain the `op.yaml` file from the last time you ran the build - so the build will fail so long as the source has already been merged before. You can test this by first cleaning `mvn clean`, and then run `mvn test` multiple times. The first time, the tests pass, the second time most tests fail because all of the matching calls have two equal matches, the third time most tests fail because all of the matching calls have three equal matches, and so on.

Honestly, what is the point in fixing this? Why would you run `mvn test` instead of `mvn clean test`?

**Comment by hinerm** [comment]
>Honestly, what is the point in fixing this? Why would you run mvn test instead of mvn clean test?

It's primarily code smell, if Ops doesn't behave like one would expect a maven project to

But as of https://github.com/scijava/incubator/commit/2fec79ee402d5422a65276a772d3bc89ae3ce8be when I run `mvn test` without `clean` multiple times in the `imagej-ops2` module, they just keep passing. So I'm going to close this and we can revisit "in the future if needed"™️
