### ISSUE TITLE
Create a "SciJava ops philosophy" document

### ISSUE THREAD

**Issue by elevans** [scijava/scijava#143]
ImageJ ops and SciJava ops clearly have distinct design philosophies that they abide by. While I know some of the reasons for why SciJava ops works the way it does, new users may be really mystified by it. Especially if they have any experience with ImageJ ops. For example when I was first interacting with SciJava ops, I thought the `ops.binary()` was a special namespace for _binary_ images. So this call: `ops.binary("filter.gauss").input(inImage, 2.0).output(outImage).computer()` had me a little confused for a moment.

I think it would be a great starting point for new and existing users (_i.e._ I'd probably would refer to it myself and share it).

**Comment by hinerm** [comment]
@elevans this is a good insight. The `binary` thing is discussed [here](https://github.com/scijava/incubator/blob/main/imagej/imagej-ops2-tutorial/docs/CallingOps.md#additions-combining-oparity) but I'm not sure that's the only place for it

**Comment by gselzer** [comment]
See also [this branch](https://github.com/scijava/incubator/tree/scijava/scijava-ops-api/package-info), where we are starting to write what an Op is, what Op equality means, etc. Adding a section on "why Ops" could make a lot of sense here, I think.

**Comment by ctrueden** [comment]
The current link for the Ops overview package-info.java is [here](https://github.com/scijava/incubator/blob/main/scijava/scijava-ops-api/src/main/java/org/scijava/ops/api/package-info.java).

As for philosophy, I'm going to paste in some words from existing sources here.

I think it is fair game to use/adapt any of the below text in the new SciJava Ops documentation.

## ImageJ wiki

From https://imagej.net/libs/imagej-ops:

<blockquote>

### Design goals

Ops has three major design goals:

1. **Easy to use and extend.** There must be a wealth of easy-to-use image processing operations (“ops”), as well as an easy framework for extending those ops in new directions.
2. **Powerful and general.** An op should be able to consist of any number of typed input and output parameters, operating on arbitrary data structures, including images of N dimensions stored in a myriad of different ways: as files on disk, programmatically generated in memory, or in remote databases. Using the powerful [ImgLib2](https://imagej.net/libs/imglib2) library achieves this ambitious goal.
3. **Very fast.** Even though ImgLib2 is vastly more general than ImageJ’s data model, that generality should not come at the expense of performance. Otherwise, users must pay a time tax to do the same things they could already do in ImageJ. The ImageJ Ops framework needs to provide a means to override *any* general-but-slow op with a faster-but-more-specific alternative, fully transparently to the user.

</blockquote>

New to SciJava Ops is the goal that all ops should match on *inputs and output types only*, never on the *values* of inputs. Reasons for that should of course be articulated in the document.

## ImageJ Ops tutorial notebook

From the [tutorial notebook](https://github.com/imagej/tutorials/blob/master/notebooks/1-Using-ImageJ/2-ImageJ-Ops.ipynb):

<blockquote>

[ImageJ Ops](https://imagej.net/ImageJ_Ops) is a library for N-dimensional image processing. The primary design goals of Ops are:

1. **Ease of use.** Ops provides a wealth of easy-to-use image processing operations ("ops").
2. **Reusability.** Ops extends Java's mantra of "[write once, run anywhere](https://en.wikipedia.org/wiki/Write_once,_run_anywhere)" to image processing algorithms. Algorithms written in the Ops framework are usable as-is from any [SciJava](https://imagej.net/SciJava)-compatible software project, such as [ImageJ](https://imagej.net/ImageJ), [CellProfiler](https://imagej.net/CellProfiler), [KNIME](https://imagej.net/KNIME), [OMERO](https://imagej.net/OMERO) and [Alida](https://imagej.net/Alida).
3. **Reproducibility.** Ops are deterministic: calling the same op twice with the same arguments yields the same result, always. And all ops are versioned.
4. **Power.** An op may consist of any number of typed input and output parameters. Ops may operate on arbitrary data structures, including images of N dimensions stored in a myriad of different ways: as files on disk, programmatically generated in memory, or in remote databases.
5. **Extensibility.** Ops provides a robust framework for writing new ops, and for extending existing ops in new directions. See the "Extending ImageJ - Ops" tutorial notebook for details.
6. **Speed.** The Ops framework provides a means to override any general-but-slow op with a faster-but-more-specific alternative, fully transparently to the user.

</blockquote>

## ImageJ2 paper

Here's the [ImageJ Ops section](https://github.com/imagej/imagej2-manuscript-2017/blob/57b1dcfd1ec8f88e011f7da2117276cdb612d3c8/imagej2.tex#L1030-L1180) of the ImageJ2 paper from 2017:

<blockquote>

ImageJ's ultimate purpose is image processing and analysis. To that end, we have crafted the ImageJ Ops component: ImageJ2's shared, extensible library of reusable image processing operations. As of version 0.33.0, the core Ops library provides 788 `Op` plugins across nearly 350 types of ops in more than 20 namespaces, covering functionality such as: image arithmetic, trigonometry, Fourier transformations, deconvolution, global and local thresholding, image statistics, image filtering, binary morphological operations, type conversion, image transformations (scaling, rotation, etc.)---even 2- and 3-dimensional geometric operations such as marching cubes 3D mesh generation (see Figure 1 for examples). A thorough treatment of available ops can be found in the ImageJ Ops tutorial notebook.

ImageJ Ops was conceived with three major design goals: 1) easy to use and extend; 2) powerful and general; and 3) high performance. To achieve all three of these goals, Ops utilizes a plugin-based design enabling ``extensible case logic.'' Ops defines a new plugin type, `Op`, each of which has a name and a list of typed parameters, analogous to a function definition in most programming languages. When invoking an op, callers typically do not specify the exact `Op` plugin to use, but instead specify the operation's name and arguments; the Ops framework then performs a *matching* process, finding the optimal fit for the given request. For example, calling `math.add` with a planar image and a 64-bit floating point number leads to a match of `net.imagej.ops.math.ConstantToPlanarImage.AddDouble`, which adds a constant value to each element of an image, whereas calling `math.add` with two planar images results in a match of `net.imagej.ops.math.IIToIIOutputII.Add`, which adds two images element-wise.

This scheme is similar to---but more powerful than---the method overloading capabilities of many programming languages: op behavior can be further specialized by tailoring `Op` implementations for specific subclasses, generic parameters, and `Converter` substitutions (see ``SciJava Common'' above). Consider an op sqrt(image), which computes the element-wise square root of an image. If we implement this op as `sqrt(Dataset)`, we miss out on performance optimizations for `ArrayImg`, an ImgLib2 container type where the entire collection of image samples is stored in a single Java primitive array. However, if we only implement `sqrt(ArrayImg)`, we are restricted in supported data types, since not all images can be stored in such a manner. The power of the Ops matching approach is that both of these and more can coexist simultaneously and extensibly, and the most specific will always be selected at runtime.

Furthermore, as algorithm implementations increasingly become available for the GPU via libraries such as OpenCL and Nvidia's CUDA, as well as for clusters via libraries such as Apache Spark, such implementations could also be expressed as ops so that they can be selected automatically based on the currently available hardware environment.

The `Op` plugin type extends SciJava's `Command`, and therefore all ops are SciJava parameterized modules, usable anywhere SciJava modules are supported---see the ``module framework'' section in ``SciJava Common'' above. Like standard modules, an op declares typed inputs and outputs. However, unlike modules in general, an op must be a ``pure function'' with a fixed number of parameters and no side effects; i.e., it must be deterministic in its behavior, operating only on the given inputs, and populating or mutating only the given outputs. These restrictions provide some very useful guarantees which allow the system to reason about an op's use and behavior; e.g., after computing an op with particular arguments once, the result can be cached to dramatically improve subsequent time performance at the potential expense of additional space. Properly constructed ops will also always be usable headless because they do not rely on the existence of UI elements.

### Op chaining and special ops

It is often the case in image processing that an algorithm can be expressed as a composition of lower level algorithms. For example, a simple difference of Gaussians (``DoG'') operation is merely two Gaussian blur operations along with a subtraction:

```
dog(image, sigma1, sigma2) = sub(gauss(image, sigma1), gauss(image, sigma2))
```

For users calling into the Ops framework via scripting, the core library provides an `eval` op backed by SciJava's expression parser library, which enables executing such sequences of ops via standard mathematical expressions, including use of unary and infix binary operators.

For developers, the Ops library provides a mechanism for efficient *chaining* of ops calls. An op may declare other ops as inputs, resulting in a tree of ops which are resolved when an op is matched; the matched op instance can then be reused across any number of input values. In this way, very general operations can be created to address a broad range of use cases---e.g., the `map` operation provides a unified way of executing an op such as `math.sqrt(number)` element-wise on a collection (e.g., an image) whose elements are numbers. Indeed, in the case of DoG, the Ops library's baseline implementation takes an image as input, along with two `filter.gauss` ops and a `math.sub` op, and then invokes them on the input image. The baseline `stats.mean` implementation is similar, built on the `stats.sum`, `stats.size` and `math.div` ops. Higher level DoG ops provide sensible defaults, enabling calls like `dog(image, sigma1, sigma2)` to work, making common operations simple, while leaving the door open for additional customization as needed.

To facilitate type-safe and efficient chaining of ops, the Ops library has a subsystem known as *special ops*. Such special ops are specifically intended to be called repeatedly from other ops, without needing to invoke the op matching algorithm every time. This repeat usage is achieved in a type-safe and efficient way by explicitly declaring the types of the op's primary inputs---i.e., the inputs whose values can be efficiently varied across invocations of the op---as well as the type of the op's primary output.

Special ops have two major characteristics beyond regular ops. First, each special op has a declared *arity*, indicating the number of primary inputs, which are explicitly typed via Java generics and can thus efficiently vary across invocations of the op. Three arities are currently implemented: *nullary* for no inputs, *unary* for one input, and *binary* for two inputs. It is important to note that unlike a formal mathematical function, a unary special op may have more than one input parameter---the ``unary'' in this case refers to the number of explicitly typed parameters intended to vary when calling an instance of the op multiple times. For instance, in the DoG example above, the baseline DoG is declared as a unary op, so that the input image can vary efficiently while the sigmas etc. are held constant in value.

Secondly, every special op is one of three kinds:

* A *function* operates on inputs, producing outputs, in a way consistent with the functional programming paradigm. Inputs are immutable, and outputs are generated during computation and subsequently also immutable. Functions are very useful for parallel processing since they are fully thread-safe even when object references overlap---but this safety comes at the expense of space, since they offer no way to reuse preallocated output buffers.
* A *computer* is similar to a function, but populates a preallocated output object instead of generating a new object every time. Computers have many of the same advantages of functions, but provide the ability to reuse preallocated output buffers to improve efficiency in space and time.
* An *inplace* op mutates its input(s) in place---i.e., its input and output are the same object. Inplace ops are highly space efficient, but lack the mathematical guarantees of functions and computers, since they destroy the original input data.

Some ops are implemented as *hybrids*, offering a choice between two or more of the function, computer and inplace computation mechanisms. Users of the ops library---even advanced users---will rarely if ever need to know about this implementation detail, but for developers crafting new ops, it is convenient to have unifying interfaces which provide common logic for combining these paradigms. See Supplemental Table 2 for a complete breakdown of the special op kinds and arities.

</blockquote>
