### ISSUE TITLE
Suggest an order for the SciJava Ops docs

### ISSUE THREAD

**Issue by elevans** [scijava/scijava#144]
The SciJava Ops documentation doesn't provide any strong indication which document should be visited first. I certainly agree that `InstallingSciJavaOpsInFiji.md` makes sense as the entry point, but what about after that? Should I go to `OpBestPractices.md`? `SearchingForOps.md`? In my experience when jumping around in those documents there were concepts I was not yet familiar with so I left those documents thinking I had stumbled into the advanced section. The best document for me after installing SciJava ops was `CallingOps.md` and `ScriptingInImageJ2.md` which broke down the bits I needed to get going.

Adding a TOC (maybe as a README?) or applying numbers to the docs might help here.

**Comment by gselzer** [comment]
Yes, some structure is definitely needed.

I was kind of waiting to do that until we put those documents on the ImageJ wiki, because I'm assuming there is some implementation-specific way to denote an ordering (like if we put it on the wiki).

@hinerm do you think these documents could go on the wiki now, or shall we add a blocked tag to this issue?
