### ISSUE TITLE
Consider merging `ScriptingInImageJ2.md` and `CallingOps.md`

### ISSUE THREAD

**Issue by elevans** [scijava/scijava#145]
In issue https://github.com/scijava/scijava/issues/144 I noted that `ScriptingInImageJ2.md` and `CallingOps.md` where the most useful for me. The `CallingOps.md` document provided the input/output information and `ScriptingInImageJ2.md` showed me how to get the op environment and provided a nice template to build off of.

I think its important to note that I was approaching this from a scripting perspective, so in that light it makes sense to merge these documents. But from a Java perspective I get why these are separate documents. Maybe there is a compromise here?

**Comment by gselzer** [comment]
Hmm. I split them because I wanted to first show an example of what "ops in the wild" might look like, and give someone a jumping-off point that isn't scary and can be copied and pasted and run immediately (putting aside the fact that the ImageJ Script Editor isn't the only place where you could run Ops).

When we have an actual user-visible location for these documents (i.e. online somewhere), I'd like to play around with merging these two, or at least saying "start at `ScriptingInImageJ2.md`" (and maybe we could create similar pages for PyImageJ or in Java) and then after they've been there link them to the `CallingOps.md` page.

But I think we're blocked by #144 first.

**Comment by elevans** [comment]
Now that the documents are accessible via ReadTheDocs I feel like this issue can be closed now. I'm happy with my ability to access the desired content easily. I also agree with your previous point about seeing "ops in the wild" versus in a scripting context.
