### ISSUE TITLE
Improve create Op logic when converting Computers to Functions

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava#28]
In order to transform a `Computer` into a `Function`, you need to find a suitable `create` Op such that, upon the user's call to the transformed `Function`, Ops can create an output suitable for the `Computer`, call that `Computer` using that created output, then return that output as a `Function` would do. As of now Ops is able to find a create `Op` in two different forms; e.g., if you are attempting to transform a `Computer3<I1, I2, I3, O>` into a `Function3<I1, I2, I3, O>`, you can either:
* find a `Source<O>` to create the output.
* find a `Function3<I1, I2, I3, O>` to create the output.

However most of our create Ops do not follow either of these patterns, since it is 
1) Difficult to make `Source`s as it is hard to create a suitable output given no constraints as inputs.
2) Impossible to cover all bases through various arity `Function<>`s.

However, there is one type of `Op` that is very common among the create Ops, being the `Function<O, O>` `Op`. Almost all `Type`s can be created in this way, `Img`s can be created in this way, etc.

Take for example a `<B extends BooleanType<B>, I2> BiComputer<B, I2, B>` that you would like to be able to use as a `BiFunction<B, I2, B>`. There is no `BiFunction<B, I2, B>` Op, nor is there a `Source<B>` Op (the latter would be easy to implement, but might have problems), and I would argue that we **should** never implement these since they could be unsafe and would definitely bloat the code base. A `Function<B, B>` create Op, however, is something that we have. It would be really nice if we were able to:
* scan the input type parameters to see if there is a suitable input `B` whose type would satisfy the output `B` (must it be an exact match? Not sure...). In this case, it is obvious the first parameter has the same type as the output.
* upon finding a suitable input type `B` in the `BiComputer`'s inputs, look for a `Function<B, B>`.
* upon finding a suitable `Function<B,B>`, convert it to a `BiFunction<B, I2, B>`.
* pass that `BiFunction<B, I2, B> to the transformer as described above.

As far as this list goes, the first two bullet points are quite easy. The third, however, will take some finesse. We know the following:
* The `Type` of the `Function` create Op that we have
* The `Type` of the `Function` that we need to convert the above `Function` to
* The index of the input that we care about and thus the indices of the inputs that we do not. Furthermore we know that the body of this `Function` that we need to convert to is essentially
```
(in0, in1, ..., sampleOutput, ..., inN-1, inN) -> {
outputFromSampleFunc.apply(sampleOutput);
};
```
Is there any way to create this?

**Comment by ctrueden** [comment]
This issue touches on two questions:

1. Given a known set of inputs, how to programmatically manufacture preallocated computer outputs?
2. How to discover and select amongst functionality intended to manufacture these outputs? The current idea is to (re)use the ops matcher, amongst ops named `create`. Is this a sound design decision—especially for `Source`-based factories?

## Regarding (1)

> Impossible to cover all bases through various arity Function<>s.

Since it is not articulated above: since writing this, @gselzer and I decided that we only want to support two kinds of `create` ops as computer output factories:

1. `Function<I1, O>`
2. `Source<O>`

That is: for higher-arity computers, we'll try to manufacture the output using only the first input. For simple cases, this is a nice and convenient default—and implementers who want to define more precisely how this is done can define their own function op that does the creation itself and delegates to the computer op.

> Difficult to make Sources as it is hard to create a suitable output given no constraints as inputs.

It depends on the type. For e.g. `DoubleType`, you don't need inputs: just `new DoubleType()`. So a `Source` is the most appropriate there.

## Regarding (2)

There is a deceptively complex question about multiple `Source` ops that return different things. Assuming we have a bunch of ops named "create" that all implement `Source` but with different types: a user who calls `ops.run("create")` with no arguments will match all of these ops, and what gets returned will be determined by priority (or else "multiple matching ops" error).

This issue is subtle and deep enough that I have filed a separate issue for it: #36.

**Comment by gselzer** [comment]
(1) has been completed via [`ComputersToFunctionsViaSource`](https://github.com/scijava/incubator/blob/master/scijava/scijava-ops/src/main/java/org/scijava/ops/adapt/functional/ComputersToFunctionsViaSource.java) and [`ComputersToFunctionsViaFunction`](https://github.com/scijava/incubator/blob/master/scijava/scijava-ops/src/main/java/org/scijava/ops/adapt/functional/ComputersToFunctionsViaFunction.java)

As far as (2) goes, we no longer provide the `ops.run("create")` syntax, and there is no way to call a `Producer` without specifying the output type (neither `OpBuilder` nor `Functions` support this).

Since the equality check issue has its own Github issue, I do not think this issue leaves anything to be addressed.
