### ISSUE TITLE
ProvenanceTest: assert that matched ops actually match

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#83]
See https://github.com/scijava/incubator/pull/46#discussion_r763349724

**Comment by gselzer** [comment]
The problem here is that these Ops will actually not be identical, as currently written.

[`DefaultOpEnvironment.opFromInfoChain`](https://github.com/scijava/incubator/blob/dd98459f77bcf954be6c47d47b9a3e071f627c13/scijava/scijava-ops-engine/src/main/java/org/scijava/ops/engine/impl/DefaultOpEnvironment.java#L293) creates a new Op *every time*. This is because the `opCache` is keyed on `MatchingConditions` (the combined `OpRef` and `Hints`); we have neither of these when we want to call this method. For that reason, in the majority of cases the two Ops created will *not* be the same. We could ensure that they are from the same `Class`, I suppose...

**Comment by gselzer** [comment]
In the case of test you commented on, that Op is a `Function` adapted from a `Computers.Arity1`, so it would take reflection to check equality beyond the wrapper (which is worth testing in and of itself)
