### ISSUE TITLE
Decide whether OpMatchingException should be a checked exception

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#85]
I know that `OpMatchingException` extends `RuntimeException` for downstream convenience—being able to pretend that everything is always going to be OK, and not forcing people to always catch the `OpMatchingException`—but I wonder if this is the wrong choice. From the Oracle Java documentation: "If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception." Is it reasonable to "recover from" a failed matching attempt? I would say yes, in the same way it's reasonable to recover from e.g. a non-existent file on the file system. Perhaps we could hedge our bets a bit, and make the matching API in `OpEnvironment` throw `OpMatchingException`, which would become checked, while `OpBuilder` could do something different, such as returning an `Optional` or null.

**Comment by gselzer** [comment]
@ctrueden if I remember correctly, downstream convenience was only one reason for making this decision, there were others:

* Internal convenience: This requires catching `OpMatchingException`s everywhere, which will clutter the code. There is a good argument here for making `OpMatchingException` checked; by wrapping nested `OpMatchingException`s, we'd have the trace of the Op calls resulting in the `OpMatchingException` (we do this already, but we could force it this way). We must be careful about preserving the trace though.

*  The tough decision about where `OpMatchingException` would live: Of course it must live in SciJava Ops API, but this `Exception` is *specific to the matcher* and shouldn't really live in `scijava.ops.api` but in `scijava.ops.api.features` if it stays in SciJava Ops API.

What if we had an checked `interface OpException extends Exception` that lived in SciJava Ops API, with other Ops-related Exceptions (`OpMatchingException`, `DependencyMatchingException`) implementing it? Then the matching API in `OpEnvironment` could throw `OpMatchingException`s. This would also let implementations be unchecked, which we could make use of in `OpBuilder`. This would also allow us to avoid throwing `OpMatchingException` in SciJava Ops API.

**Comment by gselzer** [comment]
@ctrueden do you remember the conclusions from our discussion here? Did we decide to leave them unchecked, but still declare them to be thrown in `OpEnvironment`?

**Comment by gselzer** [comment]
Looking at this over a year later, I was going to be *strongly* against making it checked, but once I realized that in (most?) scripting applications you don't have to `try`/`catch` checked exceptions I figure that users won't have to pollute their scripts with boilerplate. So that's good - users are **not** going to like the `try`/`catch` boilerplate if they have to check every single Op they call.

> From the Oracle Java documentation: "If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception." Is it reasonable to "recover from" a failed matching attempt? I would say yes, in the same way it's reasonable to recover from e.g. a non-existent file on the file system.

So I can't conceptualize *how* you'd come back from an Op matching exception, so as an example, here's the example script `DeconWithGaussian.py`:

```jython
#@ OpService ops
#@ UIService ui
#@ ImgPlus img
#@ Integer sxy
#@ Integer sz
#@ Integer numIterations
#@OUTPUT ImgPlus deconvolved

# convert to float (TODO: make sure deconvolution op works on other types)
img_float=ops.convert().float32(img)

# create and show the gaussian kernel
if img_float.numDimensions()==3:
	psf=ops.create().kernelGauss([sxy, sxy, sz])
elif img_float.numDimensions()==2:
	psf=ops.create().kernelGauss([sxy, sxy])

ui.show(psf)

# deconvolve
deconvolved=ops.deconvolve().richardsonLucyTV(img_float, psf, numIterations, 0.01)
```

@ctrueden how would you recover for each of these Op calls (assuming the script was ported to SciJava Ops and we were in Java)?

> Perhaps we could hedge our bets a bit, and make the matching API in `OpEnvironment` throw `OpMatchingException`, which would become checked, while `OpBuilder` could do something different, such as returning an `Optional` or null.

I would be *strongly* against this - returning `Optional` would add boilerplate that would *not* be escapable in scripts, and returning *null* is a huge code smell - you'd be obfuscating an `OpMatchingException` with a `NullPointerException`, assuming you're not null-checking all over the place. I'd much rather throw the checked `OpMatchingException` here, if we decide to make things checked.

**Comment by gselzer** [comment]
We're just going to leave it unchecked.
