### ISSUE TITLE
Consider whether to encapsulate javadoc access into a dedicated module

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava#89]
We may want to encapsulate the therapi usages into a single scijava-javadoc package or similar, so that the API for accessing associated javadoc of classes & fields & methods is guaranteed to be stable over time. It's less of an issue if the therapi types never leak through into our API as arguments or return values. But as soon as they do, it could break things later if therapi changes or if we replace it with something else—e.g., suppose core Java adds support for compiling in javadoc to .class files? Or suppose, for non-therapi-enriched JAR files, we look for a corresponding `-classes` JAR and read the javadoc ourselves out of there using [jdk.javadoc](https://javadoc.scijava.org/Java11/jdk.javadoc/module-summary.html) or similar.

**Comment by gselzer** [comment]
That seems fine. Due to [SciJava Discovery Therapi](https://github.com/scijava/incubator/tree/scijava/scijava-ops-engine/view-javadoc-revisions-revisions/scijava/scijava-discovery-therapi), we don't actually depend on therapi anywhere else in the incubator.

*However*, due to the modular system, all packages that want their modules read by therapi [must open themselves to it](https://github.com/scijava/incubator/blob/4a031a883578cb907717be33308fd417d9e21b7b/scijava/scijava-ops-engine/src/main/java/module-info.java#L13). I think this is about as good as we are going to get. If we wanted, I suppose we could further abstract Javadoc discovery using another module, but that might be overkill?

**Comment by gselzer** [comment]
Actually, SciJava Ops Engine was still depending on therapi, so I removed it in f3c075bb

**Comment by gselzer** [comment]
I believe that this issue can be closed by scijava/incubator#79. We have removed therapi usage entirely in favor of an annotation processor that deposits the documentation into a yaml format - we don't need runtime javadoc access anymore.
